# Generated by Django 6.0.3 on 2026-03-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, null=True),
        ),
    ]
