# Generated by Django 6.0.3 on 2026-03-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0002_expense_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, null=True),
        ),
    ]
