# Generated by Django 6.0.3 on 2026-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0006_expense_created_at_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
